# Generated by Django 3.2 on 2021-05-07 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NhanHieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenNH', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenSP', models.CharField(max_length=100)),
                ('SoLuong', models.IntegerField(blank=True, null=True)),
                ('Gia', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('TenNH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.nhanhieu')),
            ],
        ),
    ]
