# Generated by Django 3.2 on 2021-05-08 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_sanpham_tennh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='TenNH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.nhanhieu'),
        ),
    ]
