# Generated by Django 3.2.1 on 2021-05-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_sanpham_tennh'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
